- id: automation_1
  alias: Diner Lights
  trigger:
    platform: state
    entity_id: input_boolean.diner_lights
    to: 'on'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Woonkamer
      scene_name: Diner
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.diner_lights
- id: automation_2
  alias: Avond Lights
  trigger:
    platform: state
    entity_id: input_boolean.avond_lights
    to: 'on'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Woonkamer
      scene_name: Avond
  - service: light.turn_on
    data:
      entity_id: light.lamp_keukeneiland
      brightness: 10
      color_temp: 431
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.avond_lights
- id: automation_4ba
  alias: Kinderkamer Sjors te koud
  trigger:
    platform: numeric_state
    entity_id: sensor.slaapkamer_sjors_temperature
    below: 16.5
  action:
  - service: notify.all_iphones
    data:
      title: "De Molenbeemd Alerts"
      message: "Kamer Sjors te koud: {{ states('sensor.slaapkamer_sjors_temperature') }}°C"
- id: automation_4bb
  alias: Kinderkamer klein te koud
  trigger:
    platform: numeric_state
    entity_id: sensor.slaapkamer_klein_temperature
    below: 16.5
  action:
  - service: notify.all_iphones
    data:
      title: "De Molenbeemd Alerts"
      message: "Kinderkamer klein te koud: {{ states('sensor.slaapkamer_klein_temperature') }}°C"
- id: automation_4a
  alias: Doorbell pressed Test
  trigger:
    platform: state
    entity_id: input_boolean.alarm_toggle
    to: 'on'
  action:
  - service: shell_command.grab_frontdoor_image
  - service: notify.all_iphones
    data:
      message: Doorbell pressed test
      data:
        attachment:
          url: https://stevenmarcha.duckdns.org/frontdoor.jpg
          content-type: jpg
          hide-thumbnail: false
        push:
          sound: doorbell-sound-effect.wav
- id: automation_4
  alias: Doorbell pressed
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
  - service: shell_command.grab_frontdoor_image
  - service: notify.all_iphones
    data:
      message: Doorbell pressed
      data:
        attachment:
          url: https://stevenmarcha.duckdns.org/frontdoor.jpg
          content-type: jpg
          hide-thumbnail: false
        push:
          sound: doorbell-sound-effect.wav
  - condition: state
    entity_id: light.trap_spot
    state: 'off'
  - service: light.turn_on
    data:
      entity_id: light.trap_spot
      brightness: 63
      color_temp: 330
  - delay: 00:05:00
  - service: light.turn_off
    entity_id: light.trap_spot

- id: automation_5b
  alias: Doorbell ring time set
  trigger:
    platform: state
    entity_id: input_number.doorbell_ring_time
  action:
    service: mqtt.publish
    data_template:
      topic: home/doorbell/ringer/time/set
      retain: true
      payload: '{{ states(''input_number.doorbell_ring_time'') | int }}'
- id: automation_6a
  alias: Carport lights on at sunset
  trigger:
    platform: sun
    event: sunset
  action:
  - service: light.turn_on
    data:
      entity_id: light.carport
  - service: light.turn_on
    entity_id: light.lamp_voordeur
- id: automation_6b
  alias: Carport lights off at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
  - service: light.turn_off
    entity_id: light.carport, light.lamp_voordeur
- id: automation_7
  alias: Alarm clock fade in lights
  trigger:
    platform: time_pattern
    minutes: /1
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_clock_time.state
        }}'
    - condition: or
      conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.alarm_clock_status
          state: 'on'
        - condition: time
          weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.alarm_clock_weekend_status
          state: 'on'
        - condition: time
          weekday:
          - sat
          - sun
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.slaapkamer
      transition: '{{ states.sensor.alarm_clock_fade_in_minutes.state | int * 60 }}'
      profile: energize
- id: automation_8
  alias: Set Sonos Alarm Weekday
  trigger:
  - platform: state
    entity_id: input_boolean.alarm_clock_status
    to: 'on'
  action:
  - service: sonos.update_alarm
    data_template:
      entity_id: media_player.bedroom
      alarm_id: 3
      time: '{{ states.sensor.alarm_clock_time.state }}'
      enabled: true
- id: automation_8a
  alias: Set Sonos Alarm Weekend
  trigger:
  - platform: state
    entity_id: input_boolean.alarm_clock_weekend_status
    to: 'on'
  action:
  - service: sonos.update_alarm
    data_template:
      entity_id: media_player.bedroom
      alarm_id: 61
      time: '{{ states.sensor.alarm_clock_time.state }}'
      enabled: true
- id: automation_9
  alias: Disable Sonos Alarm Weekdays
  trigger:
  - platform: state
    entity_id: input_boolean.alarm_clock_status
    to: 'off'
  action:
  - service: sonos.update_alarm
    data_template:
      entity_id: media_player.bedroom
      alarm_id: 3
      enabled: false
- id: automation_9a
  alias: Disable Sonos Alarm Weekend
  trigger:
  - platform: state
    entity_id: input_boolean.alarm_clock_weekend_status
    to: 'off'
  action:
  - service: sonos.update_alarm
    data_template:
      entity_id: media_player.bedroom
      alarm_id: 61
      enabled: false
- id: automation_10
  alias: Change Alarm Clock time
  trigger:
  - platform: state
    entity_id: sensor.alarm_clock_time
  action:
  - service: sonos.update_alarm
    data_template:
      entity_id: media_player.bedroom
      alarm_id: 3
      time: '{{ states.sensor.alarm_clock_time.state }}'
  - service: sonos.update_alarm
    data_template:
      entity_id: media_player.bedroom
      alarm_id: 61
      time: '{{ states.sensor.alarm_clock_time.state }}'
- id: automation_11
  alias: All indoor lights off when holding off button
  trigger:
  - platform: state
    entity_id: sensor.slaapkamer_dimmer_switch_2, sensor.woonkamer_dimmer_switch_1
    to: 4_hold
  action:
  - service: light.turn_off
    entity_id:
    - light.keuken
    - light.lamp_keukeneiland
    - light.slaapkamer
    - light.woonkamer
    - light.overloop
    - light.tuinkamer
- id: automation_12
  alias: All indoor lights bright on when holding buttons
  trigger:
  - platform: state
    entity_id: sensor.slaapkamer_dimmer_switch_2, sensor.woonkamer_dimmer_switch_1
    to: 1_hold
  action:
  - service: light.turn_on
    entity_id:
    - light.slaapkamer
    - light.keuken
    - light.lamp_keukeneiland
    - light.woonkamer
    - light.overloop
    - light.tuinkamer
    data:
      brightness: 254
      color_temp: 200
- id: automation_13a
  alias: All indoor lights off when leaving the house
  trigger:
    platform: state
    entity_id: group.family
    to: not_home
  condition:
    condition: sun
    after: sunrise
  action:
  - service: light.turn_off
    entity_id:
    - light.slaapkamer
    - light.woonkamer
    - light.keuken
    - light.lamp_keukeneiland
    - light.overloop
    - light.tuinkamer
- id: automation_13b
  alias: Woonkamer on when coming home after dark
  trigger:
    platform: state
    entity_id: group.family
    to: home
  condition:
    condition: sun
    after: sunset
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Woonkamer
      scene_name: Avond
  - service: light.turn_on
    entity_id: light.lamp_keukeneiland, light.keuken
- id: automation_13c
  alias: Woonkamer on at sunset when not home
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: group.family
    state: not_home
  action:
  - service: light.turn_on
    entity_id:
    - light.bank_kamer
    - light.livingcolors_1
    data:
      brightness: 50
      color_temp: 366
- id: automation_13d
  alias: All off at sunrise when not home
  trigger:
    platform: sun
    event: sunrise
    offset: 00:30:00
  condition:
    condition: state
    entity_id: group.family
    state: not_home
  action:
  - service: light.turn_off
    entity_id:
    - light.slaapkamer
    - light.keuken
    - light.badkamer
    - light.lamp_keukeneiland
    - light.woonkamer
    - light.overloop
    - light.tuinkamer
- id: automation_13e
  alias: All off at night when not home
  trigger:
    platform: time
    at: "22:30:00"
  condition:
    condition: state
    entity_id: group.family
    state: not_home
  action:
  - service: light.turn_off
    entity_id:
    - light.slaapkamer
    - light.keuken
    - light.badkamer
    - light.lamp_keukeneiland
    - light.woonkamer
    - light.overloop
    - light.tuinkamer
- id: automation_15
  alias: Update Available Notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data:
      message: Update for Home Assistant is available.
- id: automation_16
  alias: Sprinkler Automation
  trigger:
    platform: state
    entity_id: switch.sprinklers_gazon
    from: 'off'
    to: 'on'
  action:
  - service: timer.start
    data_template:
      entity_id: timer.sprinkler_pump
      duration: '{% set duration = states.input_number.sprinkler_run_time.state |
        int %} {% set minutes = (duration % 60)|int  %} {% set hours = (duration /
        60)|int %} {{ "%02i:%02i:00"|format(hours, minutes) }}'
- id: automation_16a
  alias: Turn Sprinkler off at timer end
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.sprinkler_pump
  action:
  - service: switch.turn_off
    entity_id:
    - switch.sprinklers_gazon
    - switch.waterpomp
- id: automation_16b
  alias: Cancel timer on manual pump switch off
  trigger:
    platform: state
    entity_id: switch.sprinklers_gazon
    to: 'off'
  condition:
  - condition: state
    entity_id: timer.sprinkler_pump
    state: active
  action:
  - service: timer.cancel
    entity_id: timer.sprinkler_pump
- id: automation_17a
  alias: Smoke Detector Notifier
  trigger:
    platform: state
    entity_id: binary_sensor.smoke_detector_1, binary_sensor.smoke_detector_2
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: group.all_lights
    data:
      brightness: 255
  - service: notify.all_iphones
    data:
      title: Alarm!
      message: Smoke Detected!
- id: automation_17b
  alias: CO Detector Notifier
  trigger:
    platform: state
    entity_id: binary_sensor.co_detector
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: group.all_lights
    data:
      brightness: 255
  - service: notify.all_iphones
    data:
      title: Alarm!
      message: "CO Gedetecteerd, ga het huis uit!"
- id: automation_19
  alias: Save power_consumption hourly
  trigger:
    platform: time_pattern
    minutes: 0
    seconds: 0
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.power_usage_previous_hour
      value: '{{ states.sensor.energieverbruik_totaal.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.gas_usage_previous_hour
      value: '{{ states.sensor.gasverbruik_totaal.state }}'
- id: automation_19a
  alias: Save power_consumption dayly
  trigger:
    platform: time
    at: 00:00:00
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.power_usage_previous_day
      value: '{{ states.sensor.energieverbruik_totaal.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.gas_usage_previous_day
      value: '{{ states.sensor.gasverbruik_totaal.state }}'
- id: automation_20a
  alias: Turn On keuken lampen with hue remote
  trigger:
  - entity_id: sensor.woonkamer_dimmer_switch_1
    platform: state
    to: 1_click_up
  action:
  - entity_id: light.lamp_keukeneiland
    service: light.turn_on
  - service: switch.turn_on
    entity_id: switch.kerstboom
- id: automation_20b
  alias: Turn Off keuken lampen with hue remote
  trigger:
  - entity_id: sensor.woonkamer_dimmer_switch_1
    platform: state
    to: 4_click_up
  action:
  - entity_id: light.lamp_keukeneiland
    service: light.turn_off
  - service: switch.turn_off
    entity_id: switch.kerstboom
- id: automation_21
  alias: React when Opening TV
  trigger:
    platform: state
    entity_id: binary_sensor.tv_lift_up
    to: 'on'
  action:
    - service: media_player.media_pause
      entity_id: media_player.kitchen

- id: automation_23
  alias: update display
  trigger: 
    platform: state
    entity_id:  sensor.waalre_temperature, sensor.woonkamer_temperature, sensor.bbq_sensor
  action:
    - service: mqtt.publish
      data_template:
        topic: 'home/bbq/display/set'
        payload_template: '03Woonkamer:  {{states.sensor.woonkamer_temperature.state|float|round(1)}}'
    - service: mqtt.publish
      data_template:
        topic: 'home/bbq/display/set'
        payload_template: '04Buiten:     {{states.sensor.waalre_temperature.state|float|round(1)}}'
    - service: mqtt.publish
      data_template:
        topic: 'home/bbq/display/set'
        payload_template: >
          {% if states.sensor.bbq_sensor.state|int < 100 %}
            05BBQ:          {{states.sensor.bbq_sensor.state|int}}
          {% else %}
            05BBQ:         {{states.sensor.bbq_sensor.state|int}}
          {% endif %}



- id: automation_22
  alias: run sprinkler program
  trigger:
    platform: template
    value_template: "{{ states.sensor.time.state  == (states.input_datetime.sprinkler_program.attributes.timestamp | int | timestamp_custom('%H:%M', FALSE)) }}"
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.sprinkler_program_maa
            state: 'on'
          - condition: time
            weekday: mon
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.sprinkler_program_din
            state: 'on'
          - condition: time
            weekday: tue
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.sprinkler_program_woe
            state: 'on'
          - condition: time
            weekday: wed
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.sprinkler_program_don
            state: 'on'
          - condition: time
            weekday: thu
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.sprinkler_program_vri
            state: 'on'
          - condition: time
            weekday: fri
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.sprinkler_program_zat
            state: 'on'
          - condition: time
            weekday: sat
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.sprinkler_program_zon
            state: 'on'
          - condition: time
            weekday: sun
  action:
    - service: switch.turn_on
      entity_id: switch.waterpomp, switch.sprinklers_gazon

- id: automation_23a
  alias: Radio on when coming home
  trigger:
    platform: state
    entity_id: group.family
    to: 'home'
  action:
  - service: media_player.media_play
    entity_id: media_player.kitchen
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.woonkamer, media_player.kitchen
      volume_level: 0.1
- id: automation_23b
  alias: Radio off when leaving home
  trigger:
    platform: state
    entity_id: group.family
    to: 'not_home'
  action:
  - service: media_player.media_stop
    entity_id: media_player.kitchen
- id: automation_24
  alias: climate to auto when sleeping
  trigger:
    platform: time
    at: "22:00:00"
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.woonkamer, climate.badkamer
      hvac_mode: auto
- id: automation_25
  alias: Afval today
  trigger:
    platform: time
    at: "07:00:00"
  condition:
    condition: template
    value_template: "{{ 'Today' in states('sensor.waalre_gft') or 'Today' in states('sensor.waalre_papier') or 'Today' in states('sensor.waalre_pbd') or 'Today' in states('sensor.waalre_restafval') }}"
  action:
    service: notify.all_iphones
    data:
      title: Afval
      message: >
        Vandaag wordt opgehaald:
        {% if 'Today' in states('sensor.waalre_pbd') %}
        Plastic, Metaal, Drinkpakken
        {% endif %}
        {% if 'Today' in states('sensor.waalre_papier') %}
        Papier
        {% endif %}
        {% if 'Today' in states('sensor.waalre_restafval') %}
        Papier
        {% endif %}
        {% if 'Today' in states('sensor.waalre_gft') %}
        GFT
        {% endif %}

- id: automation_26
  alias: Reset afzuiging
  trigger:
    platform: state
    entity_id: switch.afzuiging_low
    to: "off"
    for: "01:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.afzuiging_low
