- id: automation_1
  alias: 'Diner Lights'
#  hide_entity: False
# initial_state: "off"
  trigger:
    platform: state
    entity_id: input_boolean.diner_lights
    to: 'on'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: 'Woonkamer'
      scene_name: 'Diner'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.diner_lights

- id: automation_2
  alias: 'Avond Lights'
#  hide_entity: False
# initial_state: "off"
  trigger:
    platform: state
    entity_id: input_boolean.avond_lights
    to: 'on'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: 'Woonkamer'
      scene_name: 'Avond'
  - service: light.turn_on
    data:
      entity_id: light.lamp_keukeneiland
      brightness: 10
      color_temp: 431
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.avond_lights

#- id: automation_3
#  alias: 'Alarm On'
#  trigger:
#    platform: state
#    entity_id: input_boolean.alarm_toggle
#    to: 'on'
#  action:
#  - service: media_player.volume_set
#    data:
#      entity_id: media_player.family_room
#      volume_level: 0.13
#  - service: media_player.select_source
#    data:
#      entity_id: media_player.family_room
#      source: "Peaceful Piano"
#  - service: media_player.play_media
#    data:
#      entity_id: media_player.family_room
#      media_content_id: "spotify:user:spotify:playlist:37i9dQZF1DX4sWSpwq3LiO"
#      media_content_type: "playlist"
#
#  - service: script.sonos_say
#    data:
#      sonos_entity: media_player.family_room
#      volume: 0.5
#      message: 'Alarm button is pressed!'
#      delay: '00:00:05'

- id: automation_4a
  alias: 'Doorbell pressed Test'
  trigger:
    platform: state
    entity_id: input_boolean.alarm_toggle
    to: 'on'
  action:
  - service: shell_command.grab_frontdoor_image 
  - service: notify.all_iphones
    data:
      message: "Doorbell pressed test"
      data:
        attachment: 
          url: !secret url_voordeur_snapshot
          content-type: jpg
          hide-thumbnail: false
        push:
          sound: "doorbell-sound-effect.wav"

- id: automation_4
  alias: 'Doorbell pressed'
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
  - service: shell_command.grab_frontdoor_image 
  - service: notify.all_iphones
    data:
      message: "Doorbell pressed"
      data:
        attachment: 
          url: !secret url_voordeur_snapshot
          content-type: jpg
          hide-thumbnail: false
        push:
          sound: "doorbell-sound-effect.wav"
  - condition: state
    entity_id: light.trap_spot
    state: 'off'    
  - service: light.turn_on
    data:
      entity_id: light.trap_spot
      brightness: 63
      color_temp: 330
  - delay: 00:05:00
  - service: light.turn_off
    entity_id: light.trap_spot

- id: automation_5
  alias: 'Doorbell Ringer off during night'
  trigger:
    platform: time
    at: '22:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.doorbell_ringer

- id: automation_5a
  alias: 'Doorbell Ringer on during day'
  trigger:
    platform: time
    at: '06:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.doorbell_ringer

- id: automation_5b
  alias: 'Doorbell ring time set'
  trigger:
    platform: state
    entity_id: input_number.doorbell_ring_time
  action:
    service: mqtt.publish
    data_template:
      topic: 'home/doorbell/ringer/time/set'
      retain: true
      payload: "{{ states('input_number.doorbell_ring_time') | int }}'\n'"

- id: automation_6a
  alias: 'Carport lights on at sunset'
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_on
      data:
        entity_id: light.carport
        #brightness: 63 
        #color_temp: 330
    - service: light.turn_on
      entity_id: light.lamp_voordeur
- id: automation_6b
  alias: 'Carport lights off at sunrise'
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      entity_id: light.carport, light.lamp_voordeur

- id: automation_7
  alias: 'Alarm clock fade in lights'
  trigger:
    platform: time
    minutes: '/1'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_clock_time.state }}'
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.alarm_clock_status
                state: 'on'
              - condition: time
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.alarm_clock_weekend_status
                state: 'on'
              - condition: time
                weekday:
                  - sat
                  - sun
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.slaapkamer
        transition: '{{ states.sensor.alarm_clock_fade_in_minutes.state | int * 60 }}'
        profile: energize

- id: automation_8
  alias: 'Set Sonos Alarm Weekday'
  trigger:
    - platform: state
      entity_id: input_boolean.alarm_clock_status
      to: 'on'
  action:
    - service: media_player.sonos_update_alarm
      data_template:
        entity_id: media_player.bedroom
        alarm_id: 3
        time: '{{ states.sensor.alarm_clock_time.state }}'
        enabled: true
- id: automation_8a
  alias: 'Set Sonos Alarm Weekend'
  trigger:
    - platform: state
      entity_id: input_boolean.alarm_clock_weekend_status
      to: 'on'
  action:
    - service: media_player.sonos_update_alarm
      data_template:
        entity_id: media_player.bedroom
        alarm_id: 61
        time: '{{ states.sensor.alarm_clock_time.state }}'
        enabled: true

- id: automation_9
  alias: 'Disable Sonos Alarm Weekdays'
  trigger:
    - platform: state
      entity_id: input_boolean.alarm_clock_status
      to: 'off'
  action:
    - service: media_player.sonos_update_alarm
      data_template:
        entity_id: media_player.bedroom
        alarm_id: 3
        enabled: false
- id: automation_9a
  alias: 'Disable Sonos Alarm Weekend'
  trigger:
    - platform: state
      entity_id: input_boolean.alarm_clock_weekend_status
      to: 'off'
  action:
    - service: media_player.sonos_update_alarm
      data_template:
        entity_id: media_player.bedroom
        alarm_id: 61
        enabled: false
    
- id: automation_10
  alias: 'Change Alarm Clock time'
  trigger:
    - platform: state
      entity_id: sensor.alarm_clock_time
  action:
    - service: media_player.sonos_update_alarm
      data_template:
        entity_id: media_player.bedroom
        alarm_id: 3
        time: '{{ states.sensor.alarm_clock_time.state }}'  
    - service: media_player.sonos_update_alarm
      data_template:
        entity_id: media_player.bedroom
        alarm_id: 61
        time: '{{ states.sensor.alarm_clock_time.state }}'  

- id: automation_11
  alias: 'All indoor lights off, climate low when holding buttons'
  trigger:
    - platform: state
      entity_id: sensor.slaapkamer_dimmer_switch_2, sensor.woonkamer_dimmer_switch_1
      to: '4_hold'
  action:
    - service: climate.set_temperature
      data:
        entity_id:
          - climate.keuken
          - climate.woonkamer
          - climate.badkamer
        temperature: 18
    - service: light.turn_off
      entity_id:
        - light.slaapkamer
        - light.woonkamer
        - light.overloop
        - light.tuinkamer
- id: automation_12
  alias: 'All indoor lights bright on when holding buttons'
  trigger:
    - platform: state
      entity_id: sensor.slaapkamer_dimmer_switch_2, sensor.woonkamer_dimmer_switch_1
      to: '1_hold'
  action:
    - service: light.turn_on
      entity_id:
        - light.slaapkamer
        - light.woonkamer
        - light.overloop
        - light.tuinkamer
      data:
        brightness: 254
        color_temp: 200

- id: automation_13a
  alias: 'All indoor lights off when leaving the house'
  trigger:
    platform: state
    entity_id: group.family
    to: 'not_home'
  condition:
    condition: sun
    after: sunrise
  action:
    - service: light.turn_off
      entity_id:
        - light.slaapkamer
        - light.woonkamer
        - light.overloop
        - light.tuinkamer
- id: automation_13b
  alias: 'Woonkamer on when coming home after dark'
  trigger:
    platform: state
    entity_id: group.family
    to: 'home'
  condition:
    condition: sun
    after: sunset
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: 'Woonkamer'
        scene_name: 'Avond'
- id: automation_13c
  alias: 'Woonkamer on at sunset when not home'
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: light.turn_on
      entity_id:
        - light.bank_kamer
      data:
        brightness: 50
        color_temp: 366
- id: automation_13d
  alias: 'All off at sunrise when not home'
  trigger:
    platform: sun
    event: sunrise
    offset: "00:30:00"
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: light.turn_off
      entity_id:
        - light.slaapkamer
        - light.woonkamer
        - light.overloop
        - light.tuinkamer

#- id: automation_14
#  alias: 'Set heating up when at work'
#  trigger:
#    platform: time
#    at: '14:00:00'
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: device_tracker.iphone_marcha
#        state: 'GGZE'
#      - condition: numeric_state
#        entity_id: sensor.woonkamer_temperature
#        below: 18
#  action:
#    service: script.early_heating
    # data_:
      #minutes_togo: {{ ( ( 20.0 - ( states.sensor.woonkamer_temperature.state | float ) ) * 60.0 ) | int }}     
      # minutes_togo: 120

- id: automation_15
  alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data:
      message: 'Update for Home Assistant is available.'

- id: automation_16
  alias: 'Sprinkler Automation'
  trigger:
    platform: state
    entity_id: switch.sprinklers_gazon
    from: 'off'
    to: 'on'
  action:
  - service: timer.start
    data_template:
      entity_id: timer.sprinkler_pump
      duration: >
        {% set duration = states.input_number.sprinkler_run_time.state | int %}
        {% set minutes = (duration % 60)|int  %}
        {% set hours = (duration / 60)|int %}
        {{ "%02i:%02i:00"|format(hours, minutes) }}

- id: automation_16a
  alias: 'Turn Sprinkler off at timer end'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.sprinkler_pump
  action:
  - service: switch.turn_off
    entity_id: 
      - switch.sprinklers_gazon
      - switch.waterpomp
- id: automation_16b
  alias: 'Cancel timer on manual pump switch off'
  trigger:
    platform: state
    entity_id: switch.sprinklers_gazon
    to: 'off'
  condition:
  - condition: state
    entity_id: timer.sprinkler_pump
    state: 'active'
  action:
  - service: timer.cancel
    entity_id: timer.sprinkler_pump

- id: automation_17
  alias: 'Smoke Detector Notifier'
  trigger:
    platform: state
    entity_id: group.smoke_detectors
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: group.all_lights
    data:
      brightness: 255
  - service: notify.all_iphones
    data:
      title: "Alarm!"
      message: "Smoke Detected!"

- id: automation_18
  alias: 'Turn on Baby feeding time lights'
  trigger:
    platform: state
    entity_id: light.dimmable_light_1
    to: 'on'
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_off
    entity_id: light.dimmable_light_2, light.dimmable_light_3
- id: automation_18a
  alias: 'Turn Off lights from baby feeding time'
  trigger:
    platform: state
    entity_id: light.dimmable_light_1
    to: 'unavailable'
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_off
    entity_id: light.babykamer
  
- id: automation_19
  alias: 'Save power_consumption hourly'
  trigger:
    platform: time
    minutes: 0
    seconds: 0
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_usage_previous_hour
        value: "{{ states.sensor.energieverbruik_totaal.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.gas_usage_previous_hour
        value: "{{ states.sensor.gasverbruik_totaal.state }}"
- id: automation_19a
  alias: 'Save power_consumption dayly'
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_usage_previous_day
        value: "{{ states.sensor.energieverbruik_totaal.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.gas_usage_previous_day
        value: "{{ states.sensor.gasverbruik_totaal.state }}"

- id: automation_20a
  alias: 'Turn On keuken lampen with hue remote'
  trigger:
    platform: state
    entity_id: sensor.woonkamer_dimmer_switch_1
    to: '1_click'
  action:
    service: light.turn_on
    entity_id: light.lamp_keukeneiland
- id: automation_20b
  alias: 'Turn Off keuken lampen with hue remote'
  trigger:
    platform: state
    entity_id: sensor.woonkamer_dimmer_switch_1
    to: '4_click'
  action:
    service: light.turn_off
    entity_id: light.lamp_keukeneiland

