- id: '1603906497133'
  alias: BME zolder Voltage Low
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 4761824a184511ebb21b759019f14b60
    entity_id: sensor.vcc_voltage
    domain: sensor
    below: 3.6
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      title: Zolder BME280 Battery Low
      message: Voltage below 2.6V for 5minutes
  mode: single
- id: '1605296475663'
  alias: Maan uit in ochtend
  description: ''
  trigger:
  - platform: time
    at: 07:00
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 5
    entity_id: light.maan
  mode: single
- id: '1606904473909'
  alias: Stoplicht Sjors onbereikbaar
  description: ''
  trigger:
  - device_id: caa868c0c10b31e0516b85abcacd3394
    domain: zha
    platform: device
    type: device_offline
    subtype: device_offline
  condition: []
  action:
  - service: notify.notify
    data:
      title: Stoplicht Sjors onbereikbaar
      message: Iemand heeft het stoplicht uitgezet
  mode: single
- id: '1606904633525'
  alias: Stoplicht Sjors Aan Rood
  description: ''
  trigger:
  - platform: time
    at: input_datetime.stoplicht_sjors_aan_rood
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 1
      color_name: red
    entity_id: light.stoplicht_sjors
  mode: single
- id: '1606905199462'
  alias: Stoplicht Sjors Aan Groen
  description: ''
  trigger:
  - platform: time
    at: input_datetime.stoplicht_sjors_aan_groen
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 1
      color_name: green
    entity_id: light.stoplicht_sjors
  mode: single
- id: '1606921959287'
  alias: Overloop Auto on Day
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 7256b65004773e0b5af456c53f6eb611
    entity_id: binary_sensor.overloop_motion_occupancy
    domain: binary_sensor
  condition:
  - condition: numeric_state
    entity_id: sensor.overloop_motion_illuminance
    below: input_number.overloop_min_lux_level
  - condition: time
    before: '22:00'
    after: 06:00
  action:
  - service: light.turn_on
    data:
      brightness: 100
      color_temp: 370
      transition: 1
    entity_id: light.overloop_zha_group_0x0005
  mode: single
- id: '1606922022104'
  alias: Overloop Auto on Night
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 7256b65004773e0b5af456c53f6eb611
    entity_id: binary_sensor.overloop_motion_occupancy
    domain: binary_sensor
  condition:
  - condition: time
    before: 06:00
    after: '22:00'
  action:
  - service: light.turn_on
    data:
      brightness: 1
      color_temp: 500
      transition: 1
    entity_id: light.overloop_zha_group_0x0005
  mode: single
- id: '1606922188780'
  alias: Overloop Auto Off
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: 7256b65004773e0b5af456c53f6eb611
    entity_id: binary_sensor.overloop_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 2
    entity_id: light.overloop_zha_group_0x0005
  mode: single
- id: '1606923541899'
  alias: Badkamer Remote On
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:17:88:01:04:f1:7a:5d
      command:
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.badkamer
  mode: single
- id: '1606923572562'
  alias: Badkamer Remote Off
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:17:88:01:04:f1:7a:5d
      command:
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.badkamer
  mode: single
- id: '1606925683072'
  alias: beweging in garage
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 205042c8383826b3301bd948db8cb8b0
    entity_id: binary_sensor.garage_motion_ias_zone
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    data:
      flash: short
    entity_id: light.hoek_kamer
  mode: single
- id: '1607009247154'
  alias: Stoplicht Sjors Uit
  description: ''
  trigger:
  - platform: time
    at: input_datetime.stoplicht_sjors_uit
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.stoplicht_sjors
  mode: single
- id: '1607949549945'
  alias: ZHA - Slaapkamer dimmer
  description: ''
  use_blueprint:
    path: vanstinator/zha-philips-hue-dimmer-switch.yaml
    input:
      brightness: '100'
      remote: 5810c16759331b6c1621eff63caca4d8
      light:
        entity_id: light.slaapkamer_zha_group_0x0006
- id: '1607949579082'
  alias: ZHA - Badkamer Remote
  description: ''
  use_blueprint:
    path: vanstinator/zha-philips-hue-dimmer-switch.yaml
    input:
      brightness: '100'
      remote: cba041246d52b6a7710d11b343bfb999
      light:
        entity_id: light.badkamer_zha_group_0x0004
- id: '1611736009587'
  alias: Maan in nachtstand
  description: ''
  trigger:
  - platform: time
    at: '21:00'
  condition:
  - condition: device
    type: is_on
    device_id: 079de496222bbccf69214d26c554e716
    entity_id: light.maan
    domain: light
  action:
  - service: light.turn_on
    data:
      brightness_pct: 20
      transition: 10
    entity_id: light.maan
  mode: single
- id: '1612552464238'
  alias: Werkplaats Afzuiging Aan
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 355533adb54b4bd5a028419a97535cb3
    entity_id: binary_sensor.tool_power_status
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 8ae8a81046c669683881f152a7992108
    entity_id: switch.werkplaats_afzuiging
    domain: switch
  mode: single
- id: '1612552530752'
  alias: Werkplaats Afzuiging Uit
  description: ''
  trigger:
  - type: turned_off
    platform: device
    device_id: 355533adb54b4bd5a028419a97535cb3
    entity_id: binary_sensor.tool_power_status
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 8ae8a81046c669683881f152a7992108
    entity_id: switch.werkplaats_afzuiging
    domain: switch
  mode: single
- id: '1613631049735'
  alias: ZHA - slaapkamer remote bed
  description: ''
  use_blueprint:
    path: poolcactus/zha_ikea_tradfri_onoff_switch_complx.yaml
    input:
      step_delay: '500'
      remote: 8b2806cf2927878c9211fb9b7ecc3334
      light:
        entity_id: light.slaapkamer_zha_group_0x0006
- id: '1613734293672'
  alias: Espresso opgewarmd
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: aa400d42ad7e7cc02177cfca0475d838
    entity_id: switch.espresso_on_off
    domain: switch
    for:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: notify.all_iphones
    data:
      title: Espresso
      message: Espresso is opgewarmd
  mode: single
- id: '1614593925186'
  alias: Canyon Road outlet
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.canyon_road_outlet
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state | int < trigger.to_state.state |
      int }}'
  action:
  - service: notify.mobile_app_iphone_steven
    data:
      message: Road outlet increase from {{trigger.from_state.state | int}} to {{trigger.to_state.state
        | int}}
      title: Canyon Road Outlet
      data:
        url: https://www.canyon.com/nl-nl/outlet-bicycles/?cgid=Outlet_all_bikes&prefn1=pc_familie&prefn2=pc_rahmengroesse&prefn3=pc_welt&prefv1=Ultimate%7CAeroad%7CEndurace&prefv2=L
  mode: single
- id: '1614950923908'
  alias: Leaving house, Radio Off
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: away
  condition: []
  action:
  - service: media_player.media_stop
    target:
      device_id: bbb039785bef4ccf9cca246b00b6d95a
  mode: single
- id: '1614951028020'
  alias: Leaving house, Radio On
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: Home
  condition: []
  action:
  - service: media_player.media_play
    target:
      entity_id:
      - media_player.kitchen
  - service: media_player.volume_set
    data:
      volume_level: 0.1
    target:
      entity_id:
      - media_player.woonkamer
      - media_player.kitchen
  mode: single
- id: '1614951167813'
  alias: 'Tv Lift: Radio Off, AppleTV On'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.tv_lift_up
    to: 'on'
  condition: []
  action:
  - service: media_player.media_pause
    target:
      entity_id: media_player.kitchen
  - service: media_player.turn_on
    target:
      entity_id: media_player.appletv_woonkamer
  mode: single
- id: '1615274760723'
  alias: 'Spiegelverwarming: Start Timer'
  description: ''
  trigger:
  - platform: state
    entity_id: switch.spiegelverwarming
    to: 'on'
  condition: []
  action:
  - service: timer.start
    data: {}
    target:
      entity_id: timer.spiegelverwarming
  mode: single
- id: '1615274912730'
  alias: 'Spiegelverwarming: Aan bij douchen'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.shower
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.waalre_temperature
    below: '22'
  action:
  - type: turn_on
    device_id: 6a46b507a92546bd94b582d2e8f29ed3
    entity_id: switch.spiegelverwarming
    domain: switch
  - service: timer.start
    data:
      duration: '0'
    target:
      entity_id: timer.spiegelverwarming
  mode: single
- id: '1615275081138'
  alias: 'Spiegelverwarming: Uit na timer of switch'
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.spiegelverwarming
  - platform: state
    entity_id: switch.spiegelverwarming
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.spiegelverwarming
  - service: timer.cancel
    target:
      entity_id: timer.spiegelverwarming
  mode: single
- id: '1615275171818'
  alias: 'Afzuiging: Reset to Low after timer'
  description: ''
  trigger:
  - platform: state
    entity_id: switch.afzuiging_low
    to: 'off'
    for: 01:30:00
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.afzuiging_low
  mode: single
- id: '1615275232810'
  alias: 'Afzuiging: Aan bij douchen'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.shower
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: 507c924ad2db4c75a0ec907cf634d232
    entity_id: switch.afzuiging_mid
    domain: switch
  mode: single
- id: '1615275401098'
  alias: 'Radio Badkamer: Koppel met Switch'
  description: Koppel aan Sonos Keuken
  trigger:
  - platform: state
    entity_id: binary_sensor.spiegelverwarming_schakelaar
    from: 'off'
    to: 'on'
  condition:
  - condition: template
    value_template: '{% if state_attr(''media_player.badkamer'', ''sonos_group'')
      | count == 1 %} true {% else %} false {% endif %}'
  action:
  - service: sonos.join
    data:
      master: media_player.kitchen
      entity_id: media_player.badkamer
  mode: single
- id: '1615275461824'
  alias: 'Radio Badkamer: Ontkoppel met Switch'
  description: Ontkoppel Sonos Badkamer
  trigger:
  - platform: state
    entity_id: binary_sensor.spiegelverwarming_schakelaar
    from: 'off'
    to: 'on'
  condition:
  - condition: template
    value_template: '{% if state_attr(''media_player.badkamer'', ''sonos_group'')
      | count > 1 %} true {% else %} false {% endif %}'
  action:
  - service: sonos.unjoin
    data:
      entity_id: media_player.badkamer
  mode: single
- id: '1615290642684'
  alias: 'Doorbell: pressed'
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: f67fcb5916ee11eba662bf0f25b58f73
    entity_id: binary_sensor.doorbell_button
    domain: binary_sensor
  condition: []
  action:
  - service: shell_command.grab_frontdoor_image
  - service: notify.all_iphones
    data:
      message: Doorbell pressed
      data:
        attachment:
          url: https://stevenmarcha.duckdns.org/frontdoor.jpg
          content-type: jpg
          hide-thumbnail: false
        push:
          sound: doorbell-sound-effect.wav
  - service: light.turn_on
    data:
      flash: short
    target:
      entity_id:
      - light.lampje_zolder
      - light.hoek_kamer
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  mode: single
- id: '1615290804191'
  alias: 'Hass Update: Notify'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: notify.mobile_app_iphone_steven
    data:
      message: Home assistant {{ state_attr('binary_sensor.updater', 'newest_version')  }}
        is available.
  mode: single
- id: '1615304007014'
  alias: 'Kartent: Reset to white'
  description: Reset to white after 2 min
  trigger:
  - platform: state
    entity_id: light.kartent
    attribute: white_value
    to: None
    for: 00:00:30
  condition: []
  action:
  - service: light.turn_on
    data:
      white_value: 100
      brightness: 100
    target:
      entity_id: light.kartent
  mode: single
- id: '1615385659393'
  alias: 'DSMR: Save Power Hourly'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '0'
    seconds: '0'
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.power_usage_previous_hour
    data_template:
      value: '{{ states(''sensor.energieverbruik_totaal'') |float }}

        '
  - service: input_number.set_value
    target:
      entity_id: input_number.gas_usage_previous_hour
    data_template:
      value: '{{ states(''sensor.water_meter_m3_sensor'') | float }}

        '
  mode: single
- id: '1615385707569'
  alias: 'DSMR: Save Power Daily'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '0'
    seconds: '0'
    hours: '0'
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.power_usage_previous_day
    data_template:
      value: '{{ states(''sensor.energieverbruik_totaal'') |float }}

        '
  - service: input_number.set_value
    target:
      entity_id: input_number.gas_usage_previous_day
    data_template:
      value: '{{ states(''sensor.water_meter_m3_sensor'') | float }}

        '
  mode: single
- id: '1615386151942'
  alias: 'Smoke Sensor: Notify People'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.smoke_detector_1,  binary_sensor.smoke_detector_2
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      entity_id: light.badkamer
  - service: notify.all_iphones
    data:
      title: Alarm! Rook in huis
      message: Ga nu het huis uit!
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
  mode: single
- id: '1615386197209'
  alias: 'CO Sensor: Notify People '
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.co_detector
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      entity_id: light.badkamer
  - service: notify.all_iphones
    data:
      title: Alarm! CO in huis
      message: Ga nu het huis uit, er is koolmonoxide gedetecteerd.
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
  mode: single
- id: '1615470843982'
  alias: 'Afval: Notify'
  description: ''
  trigger:
  - platform: time
    at: 07:00
  condition:
  - condition: template
    value_template: '{{ ''Today'' in states(''sensor.waalre_gft'') or ''Today'' in
      states(''sensor.waalre_papier'') or ''Today'' in states(''sensor.waalre_pmd'')
      or ''Today'' in states(''sensor.waalre_restafval'') }}'
  action:
  - service: notify.all_iphones
    data:
      title: Afval
      message: 'Vandaag wordt opgehaald: {% if ''Today'' in states(''sensor.waalre_pmd'')
        %} Plastic, Metaal, Drinkpakken {% endif %} {% if ''Today'' in states(''sensor.waalre_papier'')
        %} Papier {% endif %} {% if ''Today'' in states(''sensor.waalre_restafval'')
        %} Restafval {% endif %} {% if ''Today'' in states(''sensor.waalre_gft'')
        %} GFT {% endif %}

        '
  mode: single
