- platform: mqtt
  state_topic: "home/doorbell/button"
  name: "Doorbell"
  device_class: sound

- platform: template
  sensors: 
    washing_machine_status:
      friendly_name: "Washing Machine Status"
      value_template: "{{ states.sensor.washing_machine_power_now.state|int > 5 }}"
      delay_off:
        seconds: 30
      device_class: power
