- platform: generic
  name: Camera Sjors
  still_image_url: !secret camera_sjors_still_url
  stream_source: !secret camera_sjors_stream_url
  verify_ssl: false

- platform: generic
  name: Camera Hannah
  still_image_url: !secret camera_hannah_still_url
  stream_source: !secret camera_hannah_stream_url
  verify_ssl: false

- platform: generic
  name: Voordeur
  still_image_url: !secret url_voordeur_snapshot

- platform: mjpeg
  name: Camera Voordeur
  still_image_url: !secret camera_voordeur_still_url
  mjpeg_url: !secret camera_voordeur_stream_url
  verify_ssl: false

