homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  # customize: in homeassistant:, or it will fail  
  customize:
    climate.woonkamer:
      target_temp_step: 0.5

  auth_providers:
   - type: homeassistant
#   - type: legacy_api_password

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
#frontend:
#  javascript_version: latest

default_config:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path
  #  base_url: stevenmarcha.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

zone:
  name: !secret zone1_name
  latitude: !secret zone1_latitude
  longitude: !secret zone1_longitude
  radius: 300
  icon: mdi:worker
zone 2:
  name: !secret zone2_name
  latitude: !secret zone2_latitude
  longitude: !secret zone2_longitude
  icon: mdi:worker
zone 3:
  name: !secret zone3_name
  latitude: !secret zone3_latitude
  longitude: !secret zone3_longitude
  icon: mdi:weight-kilogram

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  db_url: !secret recorder_mysql_url
  exclude:
    entities:
      - sensor.time

system_health:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

person:

# Track the sun
sun:

map:

counter:

#Scene editor
scene: !include scenes.yaml

# Weather Prediction
#sensor:
#  platform: yr

# Text to speech
tts:
  platform: google_translate
  base_url: https://stevenmarcha.duckdns.org:8123

rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_556393131333514101D2-if00
#  ignore_devices:
#  - eurodomest_*
#  - f007_th_45151_*

logger:
  default: error
  #default: warning 
  logs:
    homeassistant.loader: info
    rflink: info
    #homeassistant.components.rflink: debug
    homeassistant.components.home_connect: debug

tado:
  username: !secret tado_username
  password: !secret tado_password
    
mqtt:
  broker: localhost
  client_id: home_assistant_tinysrv
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

apple_tv:
  - host: 10.1.1.24
    name: Apple TV
    login_id: !secret atv_login_id
    start_off: true
    credentials: !secret atv_credentials

ios: 

#stream:
ffmpeg:

zha:
  zigpy_config:
    network:
      channel: 15             # What channel the radio should try to use.
      channels: [15, 20, 25]  # Channel mask

home_connect:
  client_id: !secret home_connect_clientid
  client_secret: !secret home_connect_clientsecret

hue:
  bridges:
    - host: 10.1.1.10
      allow_hue_groups: true

shell_command:
  grab_frontdoor_image: /home/homeassistant/images/grabframe.sh
  test_shell_command: 'touch /home/homeassistant/images/testfile'

cover:
  - platform: template
    covers:
      tv_lift:
        friendly_name: "TV Lift"
        value_template: "{{is_state('switch.tv_lift_up','on')}}"
        open_cover:
          service: script.tv_lift_up
        close_cover:
          service: script.tv_lift_down
        stop_cover:
          service: script.tv_lift_down

notify:
  - name: all_iphones
    platform: group
    services:
      - service: mobile_app_iphone_steven
      - service: mobile_app_marcha_s_iphone

# Alarm System
alarm_control_panel:
  - platform: manual
    name: Alarm System
    code_arm_required: false
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automation
script: !include scripts.yaml
group: !include groups.yaml
light: !include lights.yaml
switch: !include switches.yaml
input_boolean: !include input_booleans.yaml
input_number: !include input_numbers.yaml
camera: !include cameras.yaml
timer: !include timers.yaml
input_datetime: !include input_datetimes.yaml
input_text: !include input_text.yaml
remote: !include remotes.yaml
plant: !include plants.yaml
