homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  # customize: in homeassistant:, or it will fail  
  customize:
    switch.doorbell_ringer:
      icon: mdi:alarm-bell
    device_tracker.iphone_marcha:
      icon: mdi:human-female
    device_tracker.iphone_steven:
      icon: mdi:human-male

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: es5

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

zone:
  name: !secret zone1_name
  latitude: !secret zone1_latitude
  longitude: !secret zone1_longitude
  radius: 300
  icon: mdi:worker
zone 2:
  name: !secret zone2_name
  latitude: !secret zone2_latitude
  longitude: !secret zone2_longitude
  icon: mdi:worker
zone 3:
  name: !secret zone3_name
  latitude: !secret zone3_latitude
  longitude: !secret zone3_longitude
  icon: mdi:weight-kilogram

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
#  db_url: mysql://hass:hass@localhost/hass

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

# Text to speech
tts:
  platform: google

rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_556393131333514101D2-if00
  ignore_devices:
    - eurodomest_*
    - f007_th_45151_*

logger:
  default: info
  logs:
    homeassistant.loader: info
    #rflink: debug
    homeassistant.components.rflink: debug

tado:
  username: !secret tado_username
  password: !secret tado_password

#climate:
#  platform: tado  
    
mqtt:
  broker: localhost
  client_id: home_assistant

apple_tv:
  - host: 10.1.1.24
    name: Apple TV
    login_id: !secret atv_login_id
    start_off: true
    credentials: !secret atv_credentials

ios:

hue:

shell_command:
  grab_frontdoor_image: /home/homeassistant/images/grabframe.sh
  test_shell_command: 'touch /home/homeassistant/images/testfile'

light:
  - platform: hue
    host: 10.1.1.10
    allow_hue_groups: true

  - platform: rflink
    automatic_add: false
    devices: 
      newkaku_5177344_1:
        name: Buiten Lamp
        signal_repetitions: 2

binary_sensor:
  - platform: mqtt
    state_topic: "home/doorbell/button"
    name: "Doorbell"
    device_class: sound

switch:
  - platform: mqtt
    name: "Doorbell Ringer"
    state_topic: "home/doorbell/ringer"
    command_topic: "home/doorbell/ringer/set"
    payload_on: "1"
    payload_off: "0"

  - platform: rflink
    devices:
      ev1527_0ec667_2:
        name: "TV Lift Down"
      ev1527_0ec667_1:
        name: "TV Lift Up"

cover:
  - platform: template
    covers:
      tv_lift:
        friendly_name: "TV Lift"
        value_template: "{{is_state('switch.tv_lift_up','on')}}"
        open_cover:
          service: script.tv_lift_up
        close_cover:
          service: script.tv_lift_down
        stop_cover:
          service: script.tv_lift_down

weather:
  - platform: yweather
    forecast: 1
    name: !secret weather_name
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
      - temperature

input_boolean:
  diner_lights:
    name: Lights in diner mode
    initial: off
    icon: mdi:lightbulb
  avond_lights:
    name: Lights in avond mode
    initial: off
    icon: mdi:lightbulb
  alarm_toggle:
    name: sound the alarm
    initial: off
    icon: mdi:lightbulb
  alarm_clock_status:
    name: Alarm set (Weekdays)
    initial: off
    icon: mdi:alarm-check
  alarm_clock_weekend_status:
    name: Alarm Set (Weekend)
    initial: off
    icon: mdi:alarm-check

input_datetime:
  alarm_clock_time_input:
    name: Alarm clock time
    has_date: false
    has_time: true

input_number:
  alarm_clock_hour:
    name: Hour
    icon: mdi:timer
    initial: 6
    min: 0
    max: 23
    step: 1
  alarm_clock_minute:
    name: Minute
    icon: mdi:timer
    initial: 0
    min: 0
    max: 59
    step: 1
  alarm_clock_fade_in_minutes:
    name: Fade In (Minutes)
    icon: mdi:gradient
    initial: 15
    min: 0
    max: 30
    step: 5

notify:
  - name: all_iphones
    platform: group
    services:
      - service: ios_iphone_steven
      - service: ios_iphone_marcha

weblink:
  entities:
    - name: Voordeur Live
      url: !secret url_voordeur_live
      icon: mdi:video
    - name: Transmission
      url: !secret url_transmission
      icon: mdi:download

history_graph:
  gr1:
    name: Temperature
    entities:
      - sensor.woonkamer_temperature
      - sensor.keuken_temperature
      - sensor.badkamer_temperature
      - sensor.slaapkamer_temperature
      - sensor.overloop_temperature
      - sensor.waalre_temperature

sensor: !include sensors.yaml
automation: !include automations.yaml
script: !include scripts.yaml
group: !include groups.yaml
