- platform: group
  name: Keuken Lampen
  entities:
    - light.keuken
    - light.lamp_keukeneiland

- platform: rflink
  automatic_add: false
  devices: 
    newkaku_5177344_1:
      name: Buiten Lamp
      signal_repetitions: 2

- platform: mqtt
  name: "Lamp Voordeur"
  state_topic: "home/sonoff_voordeur/stat/POWER"
  command_topic: "home/sonoff_voordeur/cmnd/POWER"
  availability_topic: "home/sonoff_voordeur/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Lamp Keukeneiland"
  state_topic: "home/keukeneiland/stat/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "home/keukeneiland/cmnd/POWER"
  brightness_command_topic: "home/keukeneiland/cmnd/Dimmer"
  brightness_scale: 100
  brightness_state_topic: "home/keukeneiland/stat/RESULT"
  brightness_value_template: "{{ value_json.Dimmer }}"
  color_temp_command_topic : "home/keukeneiland/cmnd/CT" 
  color_temp_state_topic: "home/keukeneiland/stat/RESULT"
  color_temp_value_template: "{{ value_json.CT }}" 
  availability_topic: "home/keukeneiland/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: group
  name: Tafel Lampen
  entities:
    - light.tafel_1
    - light.tafel_2
    - light.tafel_3
