- platform: group
  name: Keuken
  entities:
    #- light.keuken_hanglampen_zha_group_0x0007
    - light.lamp_keukeneiland
    - light.keuken_hang_links
    - light.keuken_hang_rechts

- platform: group
  name: Tafel
  entities:
    #- light.tafel_zha_group_0x0002
    - light.tafel1
    - light.tafel2
    - light.tafel3

- platform: group
  name: Woonkamer
  entities:
    #- light.woonkamer_zha_group_0x0003
    - light.tafel
    - light.hoek_kamer
    - light.woonkamer_bloom

- platform: group
  name: Carport
  entities:
    - light.carport1
    - light.carport2
    - light.carport3
    - light.lamp_voordeur

- platform: group
  name: Slaapkamer
  entities:
     #- light.slaapkamer_zha_group_0x0006
     - light.slaapkamer_spot1
     - light.slaapkamer_spot2
     - light.slaapkamer_spot3
     - light.slaapkamer_spot4
     - light.slaapkamer_spot5

- platform: group
  name: Overloop
  entities:
    #- light.overloop_zha_group_0x0006
    - light.overloop_spot_1
    - light.overloop_spot_2
    - light.overloop_spot_trap

- platform: group
  name: Badkamer
  entities:
    #- light.badkamer_zha_group_0x0004
    - light.badkamer_spot_bad_1
    - light.badkamer_spot_bad_2
    - light.badkamer_spot_bad_3
    - light.badkamer_spot_haakjes
    - light.badkamer_spot_douche
    - light.badkamer_spiegel_links
    - light.badkamer_spiegel_rechts

- platform: group
  name: Tuinkamer
  entities:
    - light.bol_tuinkamer
    - light.kartent

- platform: rflink
  automatic_add: false
  devices: 
    newkaku_5177344_1:
      name: Buiten Lamp
      signal_repetitions: 2

- platform: mqtt
  name: "Lamp Voordeur"
  state_topic: "home/sonoff_voordeur/stat/POWER"
  command_topic: "home/sonoff_voordeur/cmnd/POWER"
  availability_topic: "home/sonoff_voordeur/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Lamp Keukeneiland"
  state_topic: "home/keukeneiland/stat/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "home/keukeneiland/cmnd/POWER"
  brightness_command_topic: "home/keukeneiland/cmnd/Dimmer"
  brightness_scale: 100
  brightness_state_topic: "home/keukeneiland/stat/RESULT"
  brightness_value_template: "{{ value_json.Dimmer }}"
  color_temp_command_topic : "home/keukeneiland/cmnd/CT" 
  color_temp_state_topic: "home/keukeneiland/stat/RESULT"
  color_temp_value_template: "{{ value_json.CT }}" 
  availability_topic: "home/keukeneiland/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

