- platform: hue

- platform: mqtt
  state_topic: "raspi/temp"
  name: "Raspi Temperature"
  unit_of_measurement: "째C"
  icon_template: 'mdi:oil-temperature'
  value_template: '{{ value_json.temperature }}'
- platform: mqtt
  state_topic: "/home/DHT11/temperature"
  name: "DHT11 Temperature"
  unit_of_measurement: "째C"
- platform: mqtt
  state_topic: "/home/DHT11/humidity"
  name: "DHT11 Humidity"
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "home/doorbell/ringer/time"
  name: "Doorbell Ring Time"
  unit_of_measurement: "ms"

- platform: template
  sensors:
    energieverbruik_totaal:
      value_template: >
        {{ (float(states.sensor.energieverbruik_totaal_hoog.state) + float(states.sensor.energieverbruik_totaal_laag.state)) | round(2) }}
      unit_of_measurement: 'kWh'
- platform: template
  sensors:
    energieverbruik_per_uur:
      value_template: >
        {{ (float(states.sensor.energieverbruik_totaal.state) - float(states.input_number.power_usage_previous_hour.state)) | round(2) }}
      unit_of_measurement: 'kWh'
- platform: template
  sensors:
    gasverbruik_per_uur:
      value_template: >
        {{ (float(states.sensor.gasverbruik_totaal.state) - float(states.input_number.gas_usage_previous_hour.state)) | round(2) }}
      unit_of_measurement: 'm3'
- platform: template
  sensors:
    energieverbruik_per_dag:
      value_template: >
        {{ (float(states.sensor.energieverbruik_totaal.state) - float(states.input_number.power_usage_previous_day.state)) | round(2) }}
      unit_of_measurement: 'kWh'
- platform: template
  sensors:
    gasverbruik_per_dag:
      value_template: >
        {{ (float(states.sensor.gasverbruik_totaal.state) - float(states.input_number.gas_usage_previous_day.state)) | round(2) }}
      unit_of_measurement: 'm3'

- platform: mqtt
  state_topic: "home/smartmeter/electricity_tariff"
  name: "Energie Tarief"
  icon_template: 'mdi:theme-light-dark'
- platform: mqtt
  state_topic: "home/smartmeter/power_delivered"
  name: "Energieverbruik Actueel"
  value_template: "{{ (float(value) * 1000) | int }}"
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "W"
- platform: mqtt
  state_topic: "home/smartmeter/water_delivered"
  name: "Gasverbruik Totaal"
  icon_template: 'mdi:fire'
  unit_of_measurement: "m3"
- platform: mqtt
  state_topic: "home/smartmeter/energy_delivered_tariff1"
  name: "Energieverbruik Totaal Laag"
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "kWh"
- platform: mqtt
  state_topic: "home/smartmeter/energy_delivered_tariff2"
  name: "Energieverbruik Totaal Hoog"
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "kWh"

- platform: mqtt
  state_topic: "home/smartmeter/power_delivered_l1"
  name: "Energieverbruik Actueel L1"
  value_template: "{{ (float(value) * 1000) | int }}"
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "W"
- platform: mqtt
  state_topic: "home/smartmeter/power_delivered_l2"
  name: "Energieverbruik Actueel L2"
  value_template: "{{ (float(value) * 1000) | int }}"
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "W"
- platform: mqtt
  state_topic: "home/smartmeter/power_delivered_l3"
  name: "Energieverbruik Actueel L3"
  value_template: "{{ (float(value) * 1000) | int }}"
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "W"

- platform: mqtt
  state_topic: "home/smartmeter/voltage_l1"
  name: "Spanning L1"
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "V"
- platform: mqtt
  state_topic: "home/smartmeter/voltage_l2"
  name: "Spanning L2"
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "V"
- platform: mqtt
  state_topic: "home/smartmeter/voltage_l3"
  name: "Spanning L3"
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "V"

- platform: mqtt
  state_topic: "home/sonoffpow/tele/SENSOR"
  name: "Washing Machine Power Today"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  icon_template: 'mdi:washing_machine'
  unit_of_measurement: "KWh"
- platform: mqtt
  state_topic: "home/sonoffpow/tele/SENSOR"
  name: "Washing Machine Power Now"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  icon_template: 'mdi:washin-machine'
  unit_of_measurement: "W"
- platform: mqtt
  state_topic: "home/sonoffpow/tele/SENSOR"
  name: "Net Voltage"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "V"

- platform: mqtt
  state_topic: "home/sonoff_pomp/tele/SENSOR"
  name: "Water pump Power Now"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  icon_template: 'mdi:flash'
  unit_of_measurement: "W"
- platform: mqtt
  state_topic: "home/sonoff_pomp/tele/SENSOR"
  name: "Water pump Power Today"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  icon_template: 'mdi:flash'
  unit_of_measurement: "KWh"

- platform: template
  sensors:
    alarm_clock_time:
      friendly_name: 'Alarm Time'
      icon_template: 'mdi:alarm'
      value_template: '{{ "%0.02d:%0.02d" | format(states.input_number.alarm_clock_hour.state | int, states.input_number.alarm_clock_minute.state | int ) }}'
    alarm_clock_fade_in_minutes:
      friendly_name: 'Fade In (Minutes)'
      icon_template: 'mdi:gradient'
      value_template: '{{ states.input_number.alarm_clock_fade_in_minutes.state | int }}'
    doorbell_last_press:
      friendly_name: 'Last Doorbell Press'
      icon_template: 'mdi:clock-alert'
      value_template: '{{ as_timestamp(states.binary_sensor.doorbell.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'
    waalre_temperature:
      friendly_name: 'Waalre Weather Temperature'
      icon_template: 'mdi:temperature-celsius'
      value_template: '{{ states.weather.waalre.attributes.temperature | float }}'
      unit_of_measurement: "째C"
    overloop_lux_level:
      friendly_name: 'Overloop Lux Level'
      icon_template: 'mdi:white-balance-sunny'
      unit_of_measurement: 'lx'
      value_template: '{{ states.sensor.overloop_motion_sensor.attributes.lux | float }}'
    overloop_light_level:
      friendly_name: 'Overloop Light Level'
      icon_template: 'mdi:white-balance-sunny'
      unit_of_measurement: 'll'
      value_template: '{{ states.sensor.overloop_motion_sensor.attributes.light_level | int }}'
    overloop_temperature:
      friendly_name: 'Overloop Sensor Temperature'
      icon_template: 'mdi:temperature-celsius'
      value_template: '{{ states.sensor.overloop_motion_sensor.attributes.temperature | float }}'
      unit_of_measurement: "째C"

- platform: rflink
  automatic_add: false
