
- platform: fritzbox_netmonitor
  host: 10.1.1.2
  name: router_netmonitor

- platform: time_date
  display_options:
    - 'time'

- platform: mqtt
  state_topic: "raspi/temp"
  name: "Raspi Temperature"
  unit_of_measurement: "°C"
  icon: 'mdi:oil-temperature'
  value_template: '{{ value_json.temperature }}'

- platform: template
  sensors:
    energieverbruik_totaal:
      value_template: >
        {% if states('sensor.consumption_high_tarif_sensor') != 'unknown' and states('sensor.consumption_low_tarif_sensor') != 'unknown' %}
          {{ (states('sensor.consumption_high_tarif_sensor')|float + states('sensor.consumption_low_tarif_sensor')|float)| round(3) }}
        {% else %}
          {{ states('sensor.energieverbruik_totaal') }}
        {% endif %}
        
      unit_of_measurement: 'kWh'
    
    energieverbruik_per_uur:
      value_template: >
        {% if states('sensor.energieverbruik_totaal') != 'unknown' %}  
          {{ (states('sensor.energieverbruik_totaal')|float - states('input_number.power_usage_previous_hour')| float) | round(3) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: 'kWh'
    
    energieverbruik_per_dag:
      value_template: >
        {% if states('sensor.energieverbruik_totaal') != 'unknown' %}  
          {{ (states('sensor.energieverbruik_totaal')|float - states('input_number.power_usage_previous_day')|float) | round(3) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: 'kWh'
    
    gasverbruik_per_uur:
      value_template: >
        {% if states('sensor.water_meter_m3_sensor') != 'unknown' %}  
          {{ (states('sensor.water_meter_m3_sensor')|float - states('input_number.gas_usage_previous_hour') | float) | round(3) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: 'm3'
    
    gasverbruik_per_dag:
      value_template: >
        {% if states('sensor.water_meter_m3_sensor') != 'unknown' %}  
          {{ (states('sensor.water_meter_m3_sensor') | float - states('input_number.gas_usage_previous_day') | float) | round(3) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: 'm3'

# Internet sensors
    internet_transmission_up:
      value_template: >-
        {% if state_attr('sensor.router_netmonitor', 'transmission_rate_up') > 0 %}
          {{ (state_attr('sensor.router_netmonitor', 'transmission_rate_up') /1000 ) | round(0)  }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "kB/s"
    internet_transmission_down:
      #value_template: "{{ (state_attr('sensor.router_netmonitor', 'transmission_rate_down') /1000) | round(0) }}"
      value_template: >-
        {% if state_attr('sensor.router_netmonitor', 'transmission_rate_down') > 0 %}
          {{ (state_attr('sensor.router_netmonitor', 'transmission_rate_down') /1000 ) | round(0)  }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "kB/s"
    internet_data_sent:
      value_template: >-
        {% if state_attr('sensor.router_netmonitor', 'bytes_sent') > 0 %}
          {{ (state_attr('sensor.router_netmonitor', 'bytes_sent') /1000000000 ) | round(2)  }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "GB"
    internet_data_received:
      value_template: >-
        {% if state_attr('sensor.router_netmonitor', 'bytes_received') > 0 %}
          {{ (state_attr('sensor.router_netmonitor', 'bytes_received') /1000000000 ) | round(2)  }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "GB"

- platform: template
  sensors:
    doorbell_last_press:
      friendly_name: 'Last Doorbell Press'
      entity_id:  binary_sensor.doorbell
      icon_template: 'mdi:clock-alert'
      value_template: '{{ as_timestamp(states.binary_sensor.doorbell_button.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'


- platform: rflink
  automatic_add: false

- platform: buienradar
  name: !secret weather_name
  monitored_conditions:
    - stationname
    - conditioncode
    - condition
    - conditiondetailed
    - conditionexact
    - symbol
    - humidity
    - temperature
    - groundtemperature
    - windspeed
    - windforce
    - winddirection
    - windazimuth
    - pressure
    - visibility
    - windgust
    - precipitation
    - irradiance
    - precipitation_forecast_average
    - precipitation_forecast_total

- platform: afvalbeheer
  wastecollector: Waalre
  resources:
    - restafval
    - gft
    - papier
    - pmd
    - pbd
  postcode: 5581TL
  streetnumber: 15

- platform: mqtt
  state_topic: "/speeldoos/ads1"
  name: "Speeldoos potmeter 1"
  value_template: "{{ ((value|int)/180)|int }}"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "/speeldoos/ads2"
  name: "Speeldoos potmeter 2"
  value_template: "{{ ((value|int)/180)|int }}"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "/speeldoos/gpio2"
  name: "Speeldoos LEDs"
  value_template: "{{ value | int }}"
- platform: mqtt
  state_topic: "/speeldoos/pushmereactiontime"
  name: "Speeldoos PushMe Reaction time"
  value_template: "{{ value | int }}"
  unit_of_measurement: 'ms'

- platform: p2000
  regios: 22
  scan_interval: 30
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 1000

- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/stevenmarcha.duckdns.org/cert.pem | awk '{ print $NF }'" 
  
  #- platform: scrape
  #  name: Canyon Road outlet
  #  resource: "https://www.canyon.com/nl-nl/outlet-bicycles/?cgid=Outlet_all_bikes&prefn1=pc_rahmengroesse&prefn2=pc_welt&prefv1=L&prefv2=Road&srule=sort_last_added"
  #  select: ".js-productCount"
  #  unit_of_measurement: "items"
   
- platform: scrape
  name: Canyon Endurace WMN 7 Disc Availability
  resource: "https://www.canyon.com/nl-nl/road-bikes/endurance-bikes/endurace-wmn/endurace-7-wmn-disc/2956.html?dwvar_2956_pv_rahmenfarbe=VT%2FWH"
  #resource: "https://www.canyon.com/nl-nl/road-bikes/race-bikes/aeroad/aeroad-cf-sl-7-disc/2447.html?dwvar_2447_pv_rahmenfarbe=BK%2FGY"
  select: ".productConfiguration__availabilityMessage"
  index: 4

- platform: mqtt
  state_topic: "wodtimer/display"
  name: "WODTimer Display"
