
- platform: time_date
  display_options:
    - 'time'

- platform: template
  sensors:
    energieverbruik_totaal:
      value_template: >
        {% if states('sensor.consumption_high_tarif_sensor') != 'unknown' and states('sensor.consumption_low_tarif_sensor') != 'unknown' %}
          {{ (states('sensor.consumption_high_tarif_sensor')|float + states('sensor.consumption_low_tarif_sensor')|float)| round(3) }}
        {% else %}
          {{ states('sensor.energieverbruik_totaal') }}
        {% endif %}
      unit_of_measurement: 'kWh'
      device_class: energy
    
    energieverbruik_per_uur:
      value_template: >
        {% if states('sensor.energieverbruik_totaal') != 'unknown' %}  
          {{ (states('sensor.energieverbruik_totaal')|float - states('input_number.power_usage_previous_hour')| float) | round(3) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: 'kWh'
      device_class: energy
    
    energieverbruik_per_dag:
      value_template: >
        {% if states('sensor.energieverbruik_totaal') != 'unknown' %}  
          {{ (states('sensor.energieverbruik_totaal')|float - states('input_number.power_usage_previous_day')|float) | round(3) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: 'kWh'
      device_class: energy
    
    gasverbruik_per_uur:
      value_template: >
        {% if states('sensor.water_meter_m3_sensor') != 'unknown' %}  
          {{ (states('sensor.water_meter_m3_sensor')|float - states('input_number.gas_usage_previous_hour') | float) | round(3) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: 'm3'
      device_class: energy
    
    gasverbruik_per_dag:
      value_template: >
        {% if states('sensor.water_meter_m3_sensor') != 'unknown' %}  
          {{ (states('sensor.water_meter_m3_sensor') | float - states('input_number.gas_usage_previous_day') | float) | round(3) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: 'm3'
      device_class: energy

- platform: template
  sensors:
    doorbell_last_press:
      friendly_name: 'Last Doorbell Press'
      entity_id:  binary_sensor.doorbell
      icon_template: 'mdi:clock-alert'
      value_template: '{{ as_timestamp(states.binary_sensor.doorbell_button.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'


- platform: rflink
  automatic_add: false

- platform: afvalbeheer
  wastecollector: Waalre
  resources:
    - restafval
    - gft
    - papier
    - pmd
    - pbd
  postcode: 5581TL
  streetnumber: 15

- platform: mqtt
  state_topic: "/speeldoos/ads1"
  name: "Speeldoos potmeter 1"
  value_template: "{{ ((value|int)/180)|int }}"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "/speeldoos/ads2"
  name: "Speeldoos potmeter 2"
  value_template: "{{ ((value|int)/180)|int }}"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "/speeldoos/gpio2"
  name: "Speeldoos LEDs"
  value_template: "{{ value | int }}"
- platform: mqtt
  state_topic: "/speeldoos/pushmereactiontime"
  name: "Speeldoos PushMe Reaction time"
  value_template: "{{ value | int }}"
  unit_of_measurement: 'ms'

- platform: p2000
  regios: 22
  scan_interval: 30
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 1000

- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/stevenmarcha.duckdns.org/cert.pem | awk '{ print $NF }'" 
  
  #- platform: scrape
  #  name: Canyon Road outlet
  #  resource: "https://www.canyon.com/nl-nl/outlet-bicycles/?cgid=Outlet_all_bikes&prefn1=pc_rahmengroesse&prefn2=pc_welt&prefv1=L&prefv2=Road&srule=sort_last_added"
  #  select: ".js-productCount"
  #  unit_of_measurement: "items"
   
  #- platform: scrape
  #  name: Canyon Endurace WMN 7 Disc Availability
  #  resource: "https://www.canyon.com/nl-nl/road-bikes/endurance-bikes/endurace-wmn/endurace-7-wmn-disc/2956.html?dwvar_2956_pv_rahmenfarbe=VT%2FWH"
  #  #resource: "https://www.canyon.com/nl-nl/road-bikes/race-bikes/aeroad/aeroad-cf-sl-7-disc/2447.html?dwvar_2447_pv_rahmenfarbe=BK%2FGY"
  #  select: ".productConfiguration__availabilityMessage"
  #  index: 4

- platform: mqtt
  state_topic: "wodtimer/display"
  name: "WODTimer Display"

- platform: zwift
  username: !secret my_zwift_username
  password: !secret my_zwift_password
  #players:
  # - !secret my_friends_zwift_player_id

- platform: zwift
  username: !secret my_zwift_username_m
  password: !secret my_zwift_password_m
  #players:
  # - !secret my_friends_zwift_player_id
  #

- platform: statistics
  entity_id: sensor.ibbq_temperature_probe_1
  name: "BBQ Dome change per second in last 5 minutes"
  state_characteristic: change_second
  max_age:
    minutes: 5
  sampling_size: 50

- platform: statistics
  entity_id: sensor.ibbq_temperature_probe_2
  name: "BBQ Meat change per second in last 5 minutes"
  state_characteristic: change_second
  max_age:
    minutes: 5
  sampling_size: 50
