- platform: rflink
  devices:
    ev1527_0ec667_02:
      name: "TV Lift Down"
    ev1527_0ec667_01:
      name: "TV Lift Up"

- platform: template
  switches:
    link_sonos_woonkamer_keuken:
      value_template: "{% if 'woonkamer' in state_attr('media_player.kitchen', 'sonos_group')[1] %} true {% else %} false {% endif %}"
      turn_off:
        service: sonos.unjoin
        data: 
          entity_id: media_player.woonkamer
      turn_on:
        service: sonos.join
        data:
          master: media_player.kitchen
          entity_id: media_player.woonkamer

- platform: mqtt
  name: "Zigbee2mqtt Main join"
  state_topic: "zigbee2mqtt/bridge/config/permit_join"
  command_topic: "zigbee2mqtt/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"
