resources:
  - url: /local/mini-media-player/mini-media-player.js
    type: module
  - url: /local/button-card/button-card.js
    type: module
  
title: De Molenbeemd
excluded_entities:
views:
    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home
    # Title of the view. Will be used as the tooltip for tab icon
    title: Main 
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        title: Verlichting
        show_header_toggle: true
        entities:
          - light.woonkamer
          - light.slaapkamer
          - light.overloop
          - light.tuinkamer
          - light.keuken_lampen
          - light.babykamer
      - type: sensor
        entity: sensor.waalre_temperature_2
        name: Waalre Temperatuur
        height: 75
      - type: entities
        title: Verwarming
        entities:
          - climate.woonkamer
          - climate.tuinkamer
          - climate.slaapkamer
          - climate.slaapkamer_klein
          - climate.badkamer
      - type: entities
        title: Wij
        show_header_toggle: false
        entities:
          - device_tracker.iphone_steven
          - device_tracker.iphone_marcha
      - type: entities
        title: Deurbel
        show_header_toggle: false
        entities:
          - switch.doorbell_ringer
          - sensor.doorbell_last_press
          - input_number.doorbell_ring_time
          # - sensor.doorbell_ring_time
          - camera.voordeur
      - type: entities
        title: Wekker
        show_header_toggle: false
        entities:
          - input_boolean.alarm_clock_status
          - input_boolean.alarm_clock_weekend_status
          - sensor.alarm_clock_time

#Music Group
  - icon: mdi:music
    title: Music
    cards:
      - type: custom:mini-media-player
        entity: media_player.bedroom
        icon: 'mdi:cast'
        artwork_border: true
        hide_power: true
        show_source: true 
      - type: custom:mini-media-player
        entity: media_player.family_room
        icon: 'mdi:cast'
        artwork_border: true
        hide_power: true
        show_source: true 
      - type: custom:mini-media-player
        entity: media_player.kitchen
        icon: 'mdi:cast'
        artwork_border: true
        hide_power: true
        show_source: true 
      - type: custom:mini-media-player
        entity: media_player.apple_tv
        icon: 'mdi:cast'
        artwork_border: true
        hide_power: true

#Sprinkler Group
  - icon: mdi:water
    title: Sprinklers
    cards:
      - type: entities
        title: Tuin
        show_header_toggle: false
        entities:
          - switch.sprinklers_gazon
          - switch.waterpomp
          - input_number.sprinkler_run_time
          - timer.sprinkler_pump
          - sensor.water_pump_power_now
      - type: entities
        title: Program
        show_header_toggle: false
        entities:
          -  input_boolean.sprinkler_program_run
      - type: entities
        title: Program
        show_header_toggle: true
        entities:
          -  input_boolean.sprinkler_program_maa
          -  input_boolean.sprinkler_program_din
          -  input_boolean.sprinkler_program_woe
          -  input_boolean.sprinkler_program_woe
          -  input_boolean.sprinkler_program_don
          -  input_boolean.sprinkler_program_vri
          -  input_boolean.sprinkler_program_zat
          -  input_boolean.sprinkler_program_zon

#Babykamer Group            
  - icon: mdi:baby-buggy
    title: Babykamer
    cards:
      - type: picture-glance
        #title: Babykamer
        entities:
          - sensor.slaapkamer_klein_temperature
          - switch.dafangbaby_night_mode
        camera_image: camera.babykamer
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            color_type: blank-card
          - type: "custom:button-card"
            color_type: card
            color: rgb(245, 245, 245)
            icon: mdi:arrow-left
            action: service
            service:
              domain: mqtt
              action: publish
              data:
                topic: "home/dafangbaby/motors/horizontal/set"
                payload: "left"
          - type: "custom:button-card"
            color_type: card
            color: rgb(245, 245, 245)
            icon: mdi:arrow-up
            action: service
            service:
              domain: mqtt
              action: publish
              data:
                topic: "home/dafangbaby/motors/vertical/set"
                payload: "up"
          - type: "custom:button-card"
            color_type: card
            color: rgb(245, 245, 245)
            icon: mdi:arrow-down
            action: service
            service:
              domain: mqtt
              action: publish
              data:
                topic: "home/dafangbaby/motors/vertical/set"
                payload: "down"
          - type: "custom:button-card"
            color_type: card
            color: rgb(245, 245, 245)
            icon: mdi:arrow-right
            action: service
            service:
              domain: mqtt
              action: publish
              data:
                topic: "home/dafangbaby/motors/horizontal/set"
                payload: "right"
          - type: "custom:button-card"
            color_type: blank-card
      - type: entities
        title: Lampen
        entities:
          - light.babykamer
          - light.dimmable_light_1
          - light.dimmable_light_2
          - light.dimmable_light_3
          - light.bed_marcha

# Energy Usage Group
  - icon: mdi:flash
    title: Energy
    cards:
      - type: history-graph
        title: "Power"
        entities:
          - sensor.energieverbruik_per_uur
          - sensor.energieverbruik_per_dag
      - type: history-graph
        title: "Gas"
        entities:
          - sensor.gasverbruik_per_uur
          - sensor.gasverbruik_per_dag
      - type: entities
        title: Rookmelders
        entities:
          -  switch.smoke_detector_1
          -  switch.smoke_detector_2
      - type: entities
        title: Weer
        entities:
          - sensor.waalre_stationname
          - sensor.waalre_condition_code
          - sensor.waalre_condition
          - sensor.waalre_detailed_condition
          - sensor.waalre_full_condition
          - sensor.waalre_symbol
          - sensor.waalre_humidity
          - sensor.waalre_temperature_2
          - sensor.waalre_ground_temperature
          - sensor.waalre_wind_speed
          - sensor.waalre_wind_force
          - sensor.waalre_wind_direction
          - sensor.waalre_wind_direction_azimuth
          - sensor.waalre_pressure
          - sensor.waalre_visibility
          - sensor.waalre_wind_gust
          - sensor.waalre_precipitation
          - sensor.waalre_irradiance
          - sensor.waalre_precipitation_forecast_average
          - sensor.waalre_precipitation_forecast_total

# Camera group
  - icon: mdi:camera
    title: Cameras
    cards:
      - type: picture-glance
        entities:
          - switch.dafang2_night_mode
        camera_image: camera.woonkamer
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            color_type: blank-card
          - type: "custom:button-card"
            color_type: card
            color: rgb(245, 245, 245)
            icon: mdi:arrow-left
            action: service
            service:
              domain: mqtt
              action: publish
              data:
                topic: "home/dafang2/motors/horizontal/set"
                payload: "left"
          - type: "custom:button-card"
            color_type: card
            color: rgb(245, 245, 245)
            icon: mdi:arrow-up
            action: service
            service:
              domain: mqtt
              action: publish
              data:
                topic: "home/dafang2/motors/vertical/set"
                payload: "up"
          - type: "custom:button-card"
            color_type: card
            color: rgb(245, 245, 245)
            icon: mdi:arrow-down
            action: service
            service:
              domain: mqtt
              action: publish
              data:
                topic: "home/dafang2/motors/vertical/set"
                payload: "down"
          - type: "custom:button-card"
            color_type: card
            color: rgb(245, 245, 245)
            icon: mdi:arrow-right
            action: service
            service:
              domain: mqtt
              action: publish
              data:
                topic: "home/dafang2/motors/horizontal/set"
                payload: "right"
          - type: "custom:button-card"
            color_type: blank-card
    
