# Carport
- alias: Carport lights on at sunset
  trigger:
    platform: sun
    event: sunset
  action:
  - service: light.turn_on
    data:
      entity_id: light.carport

- alias: Carport lights off at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
  - service: light.turn_off
    entity_id: light.carport

# Leaving house
- id: automation_13a
  alias: leaving in daylight, lights off
  trigger:
    platform: state
    entity_id: group.family
    to: not_home
  condition:
    condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -6.0 #0 to -6 is dusk
  action:
  - service: light.turn_off
    entity_id:
    - light.slaapkamer
    - light.woonkamer
    - light.badkamer
    - light.keuken_lampen
    - light.overloop
    - light.tuinkamer
    - light.kartent
  - service: switch.turn_off
    entity_id:
    - switch.staande_lamp

#Coming Home
- alias: coming home in darkness, lights on
  trigger:
    platform: state
    entity_id: group.family
    to: home
  condition:
    condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: -6.0 #0 to -6 is dusk
  action:
    - service: scene.turn_on
      entity_id: scene.lampen_beneden_dag

- alias: Woonkamer on at sunset when not home
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0.0 #0 to -6 is dusk
  condition:
    condition: state
    entity_id: group.family
    state: not_home
  action:
    - service: script.verlichting_niet_thuis

# Auto Off when not home
- id: automation_13d
  alias: All off at sunrise when not home
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: 0.0 #0 to -6 is dusk
  condition:
    condition: state
    entity_id: group.family
    state: not_home
  action:
  - service: light.turn_off #all off

- id: automation_13e
  alias: All off at night when not home
  trigger:
    platform: time
    at: "22:30:00"
  condition:
    condition: state
    entity_id: group.family
    state: not_home
  action:
  - service: light.turn_off
    entity_id:
    - light.slaapkamer
    - light.keuken
    - light.badkamer
    - light.woonkamer
    - light.overloop
    - light.tuinkamer
    - light.kartent

- alias: Slaapkamer remote overloop lampen uit
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "68:0a:e2:ff:fe:12:36:f0"
      command: "off"
  action:
    service: light.turn_off
    entity_id: light.overloop_zha_group_0x0005

# Woonkamer remote
- alias: Turn On  hue woonkamer remote
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:0f:9a:13"
      command: "on"
      cluster_id: 6
      endpoint_id: 1

  action:
  - service: light.turn_on
    entity_id: light.woonkamer_zha_group_0x0003, light.tuinkamer, light.keuken_hanglampen_zha_group_0x0007, light.keukeneiland

- alias: Double click  hue woonkamer remote
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:0f:9a:13"
      command: "on_double_press"
      cluster_id: 6
      endpoint_id: 1
  action:
  - service: scene.turn_on
    entity_id: scene.lampen_beneden_dag

- alias: Turn Off woonkamer with remote
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:02:0f:9a:13"
      command: "off_with_effect"
      cluster_id: 6
      endpoint_id: 1
  action:
  - service: light.turn_off
    entity_id: light.woonkamer_zha_group_0x0003, light.tuinkamer, light.keuken_hanglampen_zha_group_0x0007, light.keukeneiland
    # - service: switch.turn_off
    #entity_id:
    #- switch.staande_lamp

# Slaapkamer Hannah
- id: automation_lights_23
  alias: Slaapkamer Hannah lights on with remote
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "68:0a:e2:ff:fe:14:a2:3e"
      command: "on"
  action:
  - service: light.turn_on
    data_template:
      entity_id: >
        {% if is_state('light.plafond_hannah2', 'on') %}
        light.plafond_hannah3
        {% elif is_state('light.plafond_hannah1', 'on') %}
        light.plafond_hannah2 
        {% else %}
        light.plafond_hannah1
        {% endif %}

- alias: Slaapkamer Hannah lights off with remote
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "68:0a:e2:ff:fe:14:a2:3e"
      command: "off"
  action:
  - service: light.turn_off
    entity_id: light.plafond_hannah1, light.plafond_hannah2, light.plafond_hannah3

# Kartent Button
- id: automation_lights_24a
  alias: Kartent lights switch single
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:12:4b:00:1f:91:57:fd"
      command: "toggle"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kartent
      hs_color: [ "{{range(0,360) | random}}", 75 ] #random color(hue)

- id: automation_lights_24b
  alias: Kartent lights switch long
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:12:4b:00:1f:91:57:fd"
      command: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kartent
      brightness: 255
      color_name: "red"
  - delay:
      milliseconds: 500
  - service: light.turn_on
    data:
      entity_id: light.kartent
      effect: "{{range(2,4) | random}}" #random effect

- id: automation_lights_24c
  alias: Kartent lights switch long
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:12:4b:00:1f:91:57:fd"
      command: "off"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kartent
      white_value: 200

- id: automation_lights_24d
  alias: Reset kartents lights after 2 minutes
  trigger:
    - platform: state
      entity_id: light.kartent
      attribute: white_value
      to: 'none'
      for:
        seconds: 30
    - platform: state
      entity_id: light.kartent
      attribute: effect
      from: 0
      for:
        seconds: 30
  action:
    - service: light.turn_on
      data:
        entity_id: light.kartent
        white_value: 100
        effect: 0

# Badkamer Remote

- alias: Turn On badkamer scene dag
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:04:f1:7a:5d"
      command: "on_triple_press"
  action:
  - service: scene.turn_on
    entity_id: scene.badkamer_dag

- alias: Turn On badkamer scene gedimd
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:04:f1:7a:5d"
      command: "on_double_press"
  action:
  - service: scene.turn_on
    entity_id: scene.badkamer_gedimd

