# Auto Off when not home
- id: automation_13d
  alias: All off at sunrise when not home
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: 0.0 #0 to -6 is dusk
  condition:
    condition: state
    entity_id: group.family
    state: not_home
  action:
  - service: light.turn_off #all off

- id: automation_13e
  alias: All off at night when not home
  trigger:
    platform: time
    at: "22:30:00"
  condition:
    condition: state
    entity_id: group.family
    state: not_home
  action:
  - service: light.turn_off
    entity_id:
    - light.slaapkamer
    - light.keuken
    - light.badkamer
    - light.woonkamer
    - light.overloop
    - light.tuinkamer
    - light.kartent

- alias: Slaapkamer remote overloop lampen uit
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "68:0a:e2:ff:fe:12:36:f0"
      command: "off"
  action:
    service: light.turn_off
    entity_id: light.overloop_zha_group_0x0005

# Slaapkamer Hannah
- id: automation_lights_23
  alias: Slaapkamer Hannah lights on with remote
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "68:0a:e2:ff:fe:14:a2:3e"
      command: "on"
  action:
  - service: light.turn_on
    data_template:
      entity_id: >
        {% if is_state('light.plafond_hannah2', 'on') %}
        light.plafond_hannah3
        {% elif is_state('light.plafond_hannah1', 'on') %}
        light.plafond_hannah2 
        {% else %}
        light.plafond_hannah1
        {% endif %}

- alias: Slaapkamer Hannah lights off with remote
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "68:0a:e2:ff:fe:14:a2:3e"
      command: "off"
  action:
  - service: light.turn_off
    entity_id: light.plafond_hannah1, light.plafond_hannah2, light.plafond_hannah3

# Kartent Button
- id: automation_lights_24a
  alias: Kartent lights switch single
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:12:4b:00:1f:91:57:fd"
      command: "toggle"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kartent
      hs_color: [ "{{range(0,360) | random}}", 75 ] #random color(hue)

- id: automation_lights_24b
  alias: Kartent lights switch long
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:12:4b:00:1f:91:57:fd"
      command: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kartent
      brightness: 255
      color_name: "red"
  - delay:
      milliseconds: 500
  - service: light.turn_on
    data:
      entity_id: light.kartent
      effect: "{{range(2,4) | random}}" #random effect

- id: automation_lights_24c
  alias: Kartent lights switch long
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:12:4b:00:1f:91:57:fd"
      command: "off"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kartent
      white_value: 200


# Badkamer Remote

- alias: Turn On badkamer scene dag
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:04:f1:7a:5d"
      command: "on_triple_press"
  action:
  - service: scene.turn_on
    entity_id: scene.badkamer_dag

- alias: Turn On badkamer scene gedimd
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:04:f1:7a:5d"
      command: "on_double_press"
  action:
  - service: scene.turn_on
    entity_id: scene.badkamer_gedimd

