
- alias: Save power consumption hourly
  trigger:
    platform: time_pattern
    minutes: 0
    seconds: 0
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.power_usage_previous_hour
      value: >
        {{ states('sensor.energieverbruik_totaal') |float }}
  - service: input_number.set_value
    data_template:
      entity_id: input_number.gas_usage_previous_hour
      value: >
        {{ states('sensor.water_meter_m3_sensor') | float }}

- alias: Save power consumption dayly
  trigger:
    platform: time
    at: 00:00:00
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.power_usage_previous_day
      value: >
        {{ states('sensor.energieverbruik_totaal') | float }}
  - service: input_number.set_value
    data_template:
      entity_id: input_number.gas_usage_previous_day
      value: >
        {{ states('sensor.water_meter_m3_sensor') | float }}
